hyperparameters:
  client:
    batch_size: 16
    local_epochs: 1
    loss: CrossEntropyLoss
    n_protos: 10
    lam: [0.1, 1]
    finetuning_epochs: 1
    malicious_percentage: [0.2, 0.4, 0.6]
    adv_factor: [1, 3]
    atk_type: [random, revert]
    model: CifarConv2
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: CifarConv2
  server:
    weighted: true
    soft: false
    K: [9, 3, 6]
    n_protos: 10
name: adversarial_proto.FedProto_C_Adv
