hyperparameters:
  client:
    batch_size: 16
    lam: [0.1, 0.5]
    local_epochs: 1
    finetuning_epochs: 1
    malicious_percentage: [0, 0.2, 0.4, 0.6, 0.8]
    adv_factor: [0.75, 1, 1.25, 2]
    atk_type: [random, revert]
    loss: CrossEntropyLoss
    model: CifarConv2_E
    n_protos: 10
    optimizer:
      lr: 0.01
      momentum: 0.9
      name: SGD
      weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  model: CifarConv2_E
  server:
    embedding_size: 1600
    n_protos: 10
    weighted: true
name: adversarial_proto.FedHP_Adv
