hyperparameters:
  client:
    batch_size: 64
    local_epochs: 1
    loss: CrossEntropyLoss
    model: CifarConv2
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: CifarConv2
  server:
    weighted: true
    soft: false
    K: 2
    anchors_per_class: 5
    random_data: true
    dataset_name: cifar10
name: fedcka.FedCKA
