hyperparameters:
  client:
    batch_size: 16
    local_epochs: 1
    loss: CrossEntropyLoss
    n_protos: 10
    lam: [1000]
    finetuning_epochs: 1
    model: CifarConv2_E
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    persistency: true
    scheduler:
      gamma: 1
      step_size: 1
  model: CifarConv2_E
  server:
    weighted: false
    embedding_size: 1600
    soft: false
    K: 9
    n_protos: 10
name: fedhp_C.FedHP_C
