hyperparameters:
  client:
    batch_size: 16
    lam: 1
    local_epochs: 1
    loss: CrossEntropyLoss
    model: CifarConv2
    finetuning_epochs: 1
    n_protos: 10
    optimizer:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
    scheduler:
      gamma: 1
      step_size: 1
  model: CifarConv2
  server:
    n_protos: 10
    weighted: false
name: fluke.algorithms.fedproto.FedProto
